### ISSUE TITLE
Ecuador's government budget 2015

### ISSUE THREAD

**Issue by edobejar** [datasets/registry#89] opened 2015-04-21 02:28 UTC
Hi, 

This is my first datapackage. It's about Ecuador's government budget for 2015:
https://github.com/edobejar/presupuesto

Edo

**Comment by Yannael** [comment] 2015-04-21 18:29
Great!
The data from the 'Data table' is however not displayed for me at 
http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fedobejar%2Fpresupuesto
(trying with Firefox/Chrome/Safari on Mac OS 10.7.5)

Not sure what the problem is. @rgrp any idea?

Datapackage.json infos:
* For the license, you should use an array, such as described in 
http://dataprotocols.org/data-packages/
and add the link in the license section of the Readme
*  It would be good to add the 'sources' field
So the 'source' appears on the viewer such as in:
http://data.okfn.org/data/core/language-codes
* Additionally you may add the 'contributors' and 'maintainers' fields if you wish to keep responsibility for the package.
Thanks!

**Comment by edobejar** [comment] 2015-04-21 19:52
Done! Regarding the viewer, added quotes for each value, and also left the header without quotes:
http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fedobejar%2Fpresupuesto

And updated also datapackage.json with your suggestions.

**Comment by edobejar** [comment] 2015-04-21 19:52
By the way, at 
http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fedobejar%2Fpresupuesto
when I click the Metadata box (top right) I get not found. Any ideas?

**Comment by Yannael** [comment] 2015-04-22 17:20
Ok - looks good!

For the broken link in the Metadata box, the issue should be fixed once the package is moved to the  core repository.

@rgrp Can it be moved it to the core repository?

**Comment by rgrp** [comment] 2015-05-02 13:06
@Yannael yes this might be better as part of http://OpenSpending.org - @Yannael and @edobejar we are just in the midst of rebooting this work and process in OpenSpending - perhaps we finalise here and then see where we locate this data package.

@edobejar would you like to look at https://discuss.okfn.org/c/openspending and the various threads to get some context - I'd also be interested in your thoughts and feedback.

**Comment by Yannael** [comment] 2015-05-04 05:53
@rgrp @edobejar Added to catalog-list

**Comment by rgrp** [comment] 2015-05-17 16:07
@Yannael can we close this as FIXED w00t!

**Closed** 2015-05-18 07:12 UTC
